const DataJewelryMen = {
  productDataJewelryMen: [
    {
      id: 1,
      cover: "/DataImages/jewelry/men/jewelry_m_1.jpg",
      name: "RAPTOR ",
      desc: 'Raptor Automatic',
      size: '42 MM',
      price: 18658,
      sex: 'men',
      product: 'jewelry',
      display: 1,

    },
    {
      id: 2,
      cover: "/DataImages/jewelry/men/jewelry_m_2.jpg",
      name: "RAPTOR ",
      desc: 'Raptor Automatic',
      size: '42 MM',
      price: 18658,
      sex: 'men',
      product: 'jewelry',
      display: 2,

    },
    {
      id: 3,
      cover: "/DataImages/jewelry/men/jewelry_m_3.jpg",
      name: "RAPTOR ",
      desc: 'Raptor Automatic',
      size: '42 MM',
      price: 18658,
      sex: 'men',
      product: 'jewelry',
      display: 3,

    },
    {
      id: 4,
      cover: "/DataImages/jewelry/men/jewelry_m_4.jpg",
      name: "RAPTOR ",
      desc: 'Raptor Automatic',
      size: '42 MM',
      price: 18658,
      sex: 'men',
      product: 'jewelry',
      display: 4,

    },
    {
      id: 5,
      cover: "/DataImages/jewelry/men/jewelry_m_5.jpg",
      name: "RAPTOR ",
      desc: 'Raptor Automatic',
      size: '42 MM',
      price: 18658,
      sex: 'men',
      product: 'jewelry',
      display: 5,

    },
    {
      id: 6,
      cover: "/DataImages/jewelry/men/jewelry_m_6.jpg",
      name: "RAPTOR ",
      desc: 'Raptor Automatic',
      size: '42 MM',
      price: 18658,
      sex: 'men',
      product: 'jewelry',
      display: 6,
    },
    {
      id: 7,
      cover: "/DataImages/jewelry/men/jewelry_m_7.jpg",
      name: "RAPTOR ",
      desc: 'Raptor Automatic',
      size: '42 MM',
      price: 18658,
      sex: 'men',
      product: 'jewelry',
      display: 7,
    },
    {
      id: 8,
      cover: "/DataImages/jewelry/men/jewelry_m_8.jpg",
      name: "RAPTOR ",
      desc: 'Raptor Automatic',
      size: '42 MM',
      price: 18658,
      sex: 'men',
      product: 'jewelry',
      display: 8,
    },
    {
      id: 9,
      cover: "/DataImages/jewelry/men/jewelry_m_9.jpg",
      name: "RAPTOR ",
      desc: 'Raptor Automatic',
      size: '42 MM',
      price: 18658,
      sex: 'men',
      product: 'jewelry',
      display: 9,

    },
    {
      id: 10,
      cover: "/DataImages/jewelry/men/jewelry_m_10.jpg",
      name: "RAPTOR ",
      desc: 'Raptor Automatic',
      size: '42 MM',
      price: 18658,
      sex: 'men',
      product: 'jewelry',
      display: 10,

    },
    {
      id: 11,
      cover: "/DataImages/jewelry/men/jewelry_m_11.jpg",
      name: "RAPTOR ",
      desc: 'Raptor Automatic',
      size: '42 MM',
      price: 18658,
      sex: 'men',
      product: 'jewelry',
      display: 11,

    },
    {
      id: 12,
      cover: "/DataImages/jewelry/men/jewelry_m_12.jpg",
      name: "RAPTOR ",
      desc: 'Raptor Automatic',
      size: '42 MM',
      price: 18658,
      sex: 'men',
      product: 'jewelry',
      display: 12,

    },
  ]
}

export default DataJewelryMen