export const DataDetails = {
  productDataDetails: [
    {
      id: 1,
      img_1: "/DataImages/dataDetails/watches_men/id_1/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_1/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_1/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_1/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_1/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_1/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_1/7.jpg",
      img_8: "/DataImages/dataDetails/watches_men/id_1/8.jpeg",
      video_2: "/DataImages/dataDetails/watches_men/id_1/9.mp4",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'watches',
    },
    {
      id: 2,
      img_1: "/DataImages/dataDetails/watches_men/id_2/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_2/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_2/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_2/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_2/5.jpg",
      video_1: "/DataImages/dataDetails/watches_men/id_2/6.mp4",
      video_2: "/DataImages/dataDetails/watches_men/id_2/7.mp4",
      name: "CHRONO CERAMIC ",
      size: '45MM',
      desc: 'Gloss White',
      price: 11165,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 3,
      img_1: "/DataImages/dataDetails/watches_men/id_3/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_3/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_3/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_3/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_3/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_3/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_3/7.jpg",
      video_1: "/DataImages/dataDetails/watches_men/id_3/8.mp4",
      video_2: "/DataImages/dataDetails/watches_men/id_3/9.mp4",
      name: "CHRONO CERAMIC ",
      size: '45MM',
      desc: 'Midnight Blue',
      price: 11100,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 4,
      img_1: "/DataImages/dataDetails/watches_men/id_4/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_4/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_4/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_4/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_4/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_4/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_4/7.jpg",
      img_8: "/DataImages/dataDetails/watches_men/id_4/8.jpeg",
      video_2: "/DataImages/dataDetails/watches_men/id_4/9.mp4",
      name: "AIRHAWK ",
      size: '45MM',
      desc: 'Skyline Silver',
      price: 11165,
      sex: 'men',

      product: 'watches',
    },
    {
      id: 5,
      img_1: "/DataImages/dataDetails/watches_men/id_5/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_5/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_5/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_5/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_5/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_5/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_5/7.jpg",
      video_1: "/DataImages/dataDetails/watches_men/id_5/8.mp4",
      video_2: "/DataImages/dataDetails/watches_men/id_5/9.mp4",
      name: "LEGACY SLIM  ",
      size: '42MM',
      desc: 'Panther Black',
      price: 4421,
      sex: 'men',

      product: 'watches',
    },
    {
      id: 6,
      img_1: "/DataImages/dataDetails/watches_men/id_6/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_6/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_6/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_6/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_6/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_6/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_6/7.jpg",
      img_8: "/DataImages/dataDetails/watches_men/id_6/8.jpeg",
      video_2: "/DataImages/dataDetails/watches_men/id_6/9.mp4",
      name: "AIRHAWK  ",
      size: '42MM',
      desc: 'Honey Smoke',
      price: 8543,
      sex: 'men',

      product: 'watches',
    },
    {
      id: 7,
      img_1: "/DataImages/dataDetails/watches_men/id_7/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_7/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_7/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_7/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_7/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_7/6.jpg",
      video_1: "/DataImages/dataDetails/watches_men/id_7/7.mp4",
      video_2: "/DataImages/dataDetails/watches_men/id_7/8.mp4",
      name: "LEGACY SLIM",
      size: '42MM',
      desc: 'Manta Blue',
      price: 4421,
      sex: 'men',

      product: 'watches', group: 1,
    },
    {
      id: 8,
      img_1: "/DataImages/dataDetails/watches_men/id_8/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_8/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_8/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_8/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_8/5.jpg",
      video_1: "/DataImages/dataDetails/watches_men/id_8/6.mp4",
      video_2: "/DataImages/dataDetails/watches_men/id_8/7.mp4",
      name: "LEGACY SLIM",
      size: '42MM',
      desc: 'Eagle Tan',
      price: 4421,
      sex: 'men',

      product: 'watches', group: 1,
    },
    {
      id: 9,
      img_1: "/DataImages/dataDetails/watches_men/id_9/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_9/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_9/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_9/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_9/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_9/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_9/7.jpg",
      img_8: "/DataImages/dataDetails/watches_men/id_9/8.jpeg",
      video_2: "/DataImages/dataDetails/watches_men/id_9/9.mp4",
      name: "AIRHAWK",
      size: '42MM',
      desc: 'Stealth Black',
      price: 8500,
      sex: 'men',

      product: 'watches',
    },
    {
      id: 10,
      img_1: "/DataImages/dataDetails/watches_men/id_10/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_10/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_10/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_10/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_10/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_10/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_10/7.jpg",
      video_1: "/DataImages/dataDetails/watches_men/id_10/8.mp4",
      video_2: "/DataImages/dataDetails/watches_men/id_10/9.mp4",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Moon Silver',
      price: 9292,
      sex: 'men',

      product: 'watches',
    },
    {
      id: 11,
      img_1: "/DataImages/dataDetails/watches_men/id_11/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_11/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_11/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_11/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_11/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_11/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_11/7.jpg",
      img_8: "/DataImages/dataDetails/watches_men/id_11/8.jpeg",
      video_2: "/DataImages/dataDetails/watches_men/id_11/9.mp4",
      name: "AIRHAWK",
      size: '42MM',
      desc: 'Maple Frost',
      price: 8540,
      sex: 'men',

      product: 'watches',
    },
    {
      id: 12,
      img_1: "/DataImages/dataDetails/watches_men/id_12/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_12/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_12/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_12/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_12/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_12/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_12/7.jpg",
      video_1: "/DataImages/dataDetails/watches_men/id_12/8.mp4",
      video_2: "/DataImages/dataDetails/watches_men/id_12/9.mp4",
      name: "LEGACY SLIM",
      size: '42MM',
      desc: 'Grizzly Brown',
      price: 4400,
      sex: 'men',

      product: 'watches',
    },
    {
      id: 13,
      img_1: "/DataImages/dataDetails/watches_men/id_13/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_13/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_13/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_13/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_13/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_13/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_13/7.jpg",
      video_1: "/DataImages/dataDetails/watches_men/id_13/8.mp4",
      img_9: "/DataImages/dataDetails/watches_men/id_13/9.jpeg",
      name: "ELEMENT CERAMIC",
      size: '43MM',
      desc: 'Gloss White',
      price: 8300,
      sex: 'men',

      product: 'watches',
    },
    {
      id: 14,
      img_1: "/DataImages/dataDetails/watches_men/id_14/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_14/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_14/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_14/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_14/5.jpeg",
      img_6: "/DataImages/dataDetails/watches_men/id_14/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_14/7.jpg",
      img_8: "/DataImages/dataDetails/watches_men/id_14/8.jpeg",
      img_9: "/DataImages/dataDetails/watches_men/id_14/9.jpg",
      name: "BLACKTOP",
      size: '47MM',
      desc: 'Astro Blue',
      price: 9292,
      sex: 'men',

      product: 'watches',
    },
    {
      id: 15,
      img_1: "/DataImages/dataDetails/watches_men/id_15/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_15/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_15/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_15/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_15/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_15/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_15/7.jpg",
      video_1: "/DataImages/dataDetails/watches_men/id_15/8.mp4",
      video_2: "/DataImages/dataDetails/watches_men/id_15/9.mp4",
      name: "LEGACY SLIM",
      size: '42MM',
      desc: 'Phoenix Gold',
      price: 4790,
      sex: 'men',

      product: 'watches',
    },
    {
      id: 16,
      img_1: "/DataImages/dataDetails/watches_men/id_16/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_16/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_16/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_16/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_16/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_16/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_16/7.jpg",
      video_1: "/DataImages/dataDetails/watches_men/id_16/8.mp4",
      video_2: "/DataImages/dataDetails/watches_men/id_16/9.mp4",
      name: "VOYAGER",
      size: '42MM',
      desc: 'Eclipse Gold',
      price: 5902,
      sex: 'men',

      product: 'watches',
    },
    {
      id: 17,
      img_1: "/DataImages/dataDetails/watches_men/id_17/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_17/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_17/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_17/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_17/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_17/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_17/7.jpg",
      video_1: "/DataImages/dataDetails/watches_men/id_17/8.mp4",
      video_2: "/DataImages/dataDetails/watches_men/id_17/9.mp4",
      name: "BLACKTOP",
      size: '47MM',
      desc: 'Champion Gold',
      price: 9292,
      sex: 'men',

      product: 'watches',
    },
    {
      id: 18,
      img_1: "/DataImages/dataDetails/watches_men/id_18/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_18/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_18/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_18/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_18/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_18/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_18/7.jpg",
      video_1: "/DataImages/dataDetails/watches_men/id_18/8.mp4",
      video_2: "/DataImages/dataDetails/watches_men/id_18/9.mp4",
      name: "BLACKTOP",
      size: '47MM',
      desc: 'Rallye Green',
      price: 9292,
      sex: 'men',

      product: 'watches',
    },
    {
      id: 19,
      img_1: "/DataImages/dataDetails/watches_men/id_19/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_19/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_19/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_19/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_19/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_19/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_19/7.jpg",
      video_1: "/DataImages/dataDetails/watches_men/id_19/8.mp4",
      video_2: "/DataImages/dataDetails/watches_men/id_19/9.mp4",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Honey Smoke',
      price: 9929,
      sex: 'men',

      product: 'watches',
    },
    {
      id: 20,
      img_1: "/DataImages/dataDetails/watches_men/id_20/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_20/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_20/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_20/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_20/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_20/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_20/7.jpg",
      video_1: "/DataImages/dataDetails/watches_men/id_20/8.mp4",
      img_9: "/DataImages/dataDetails/watches_men/id_20/9.jpeg",
      name: "ELEMENT CERAMIC",
      size: '43MM',
      desc: 'Midnight Blue',
      price: 5443,
      sex: 'men',

      product: 'watches',
    },
    {
      id: 21,
      img_1: "/DataImages/dataDetails/watches_men/id_21/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_21/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_21/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_21/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_21/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_21/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_21/7.jpg",
      video_1: "/DataImages/dataDetails/watches_men/id_21/8.mp4",
      img_9: "/DataImages/dataDetails/watches_men/id_21/9.jpeg",
      name: "ELEMENT CERAMIC",
      size: '43MM',
      desc: 'Midnight Blue',
      price: 5443,
      sex: 'men',

      product: 'watches',
    },
    {
      id: 22,
      img_1: "/DataImages/dataDetails/watches_men/id_22/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_22/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_22/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_22/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_22/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_22/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_22/7.jpg",
      video_1: "/DataImages/dataDetails/watches_men/id_22/8.mp4",
      video_2: "/DataImages/dataDetails/watches_men/id_22/9.mp4",
      name: "ELEMENT CERAMIC",
      size: '43MM',
      desc: 'Midnight Blue',
      price: 5443,
      sex: 'men',

      product: 'watches',
    },
    {
      id: 23,
      img_1: "/DataImages/dataDetails/watches_men/id_23/1.jpg",
      img_2: "/DataImages/dataDetails/watches_men/id_23/2.jpg",
      img_3: "/DataImages/dataDetails/watches_men/id_23/3.jpg",
      img_4: "/DataImages/dataDetails/watches_men/id_23/4.jpg",
      img_5: "/DataImages/dataDetails/watches_men/id_23/5.jpg",
      img_6: "/DataImages/dataDetails/watches_men/id_23/6.jpg",
      img_7: "/DataImages/dataDetails/watches_men/id_23/7.jpg",
      img_8: "/DataImages/dataDetails/watches_men/id_23/8.jpeg",
      img_9: "/DataImages/dataDetails/watches_men/id_23/9.jpeg",
      name: "ELEMENT CERAMIC",
      size: '43MM',
      desc: 'Midnight Blue',
      price: 5443,
      sex: 'men',

      product: 'watches',
    },









    // ---------------------------------- women -------------------------------------------
    {
      id: 1,
      img_1: "/DataImages/dataDetails/watches_women/id_1/1.jpg",
      img_2: "/DataImages/dataDetails/watches_women/id_1/2.jpg",
      img_3: "/DataImages/dataDetails/watches_women/id_1/3.mp4",
      img_4: "/DataImages/dataDetails/watches_women/id_1/4.jpg",
      img_5: "/DataImages/dataDetails/watches_women/id_1/5.jpg",
      img_6: "/DataImages/dataDetails/watches_women/id_1/6.jpg",
      img_7: "/DataImages/dataDetails/watches_women/id_1/7.jpg",
      video_1: "/DataImages/dataDetails/watches_women/id_1/8.mp4",
      video_2: "/DataImages/dataDetails/watches_women/id_1/9.mp4",
      name: "ELEMENT CERAMIC",
      size: '43MM',
      desc: 'Midnight Blue',
      price: 5443,
      sex: 'women',
      product: 'watches',
    },
    {
      id: 2,
      img_1: "/DataImages/dataDetails/watches_women/id_2/1.jpg",
      img_2: "/DataImages/dataDetails/watches_women/id_2/2.jpg",
      img_3: "/DataImages/dataDetails/watches_women/id_2/3.mp4",
      img_4: "/DataImages/dataDetails/watches_women/id_2/4.jpg",
      img_5: "/DataImages/dataDetails/watches_women/id_2/5.jpg",
      img_6: "/DataImages/dataDetails/watches_women/id_2/6.jpg",
      img_7: "/DataImages/dataDetails/watches_women/id_2/7.jpg",
      img_8: "/DataImages/dataDetails/watches_women/id_2/8.jpeg",
      img_9: "/DataImages/dataDetails/watches_women/id_2/9.jpeg",
      name: "SIGNATURE SQUARE CERAMIC ",
      desc: 'Gloss White',
      size: '26MM',
      price: 8588,
      sex: 'women',
      product: 'watches',
    },
    {
      id: 3,
      img_1: "/DataImages/dataDetails/watches_women/id_3/1.jpg",
      img_2: "/DataImages/dataDetails/watches_women/id_3/2.jpg",
      img_3: "/DataImages/dataDetails/watches_women/id_3/3.mp4",
      img_4: "/DataImages/dataDetails/watches_women/id_3/4.jpg",
      img_5: "/DataImages/dataDetails/watches_women/id_3/5.jpg",
      img_6: "/DataImages/dataDetails/watches_women/id_3/6.jpg",
      img_7: "/DataImages/dataDetails/watches_women/id_3/7.jpg",
      img_8: "/DataImages/dataDetails/watches_women/id_3/8.jpeg",
      img_9: "/DataImages/dataDetails/watches_women/id_3/9.jpeg",
      name: "SIGNATURE SQUARE CERAMIC",
      desc: ' Cashmere Taupe',
      size: '26MM',
      price: 8588,
      sex: 'women',
      product: 'watches',
    },
    {
      id: 4,
      img_1: "/DataImages/dataDetails/watches_women/id_4/1.jpg",
      img_2: "/DataImages/dataDetails/watches_women/id_4/2.jpg",
      img_3: "/DataImages/dataDetails/watches_women/id_4/3.mp4",
      img_4: "/DataImages/dataDetails/watches_women/id_4/4.jpg",
      img_5: "/DataImages/dataDetails/watches_women/id_4/5.jpg",
      img_6: "/DataImages/dataDetails/watches_women/id_4/6.jpg",
      img_7: "/DataImages/dataDetails/watches_women/id_4/7.jpg",
      video_1: "/DataImages/dataDetails/watches_women/id_4/8.mp4",
      img_9: "/DataImages/dataDetails/watches_women/id_4/9.jpeg",
      name: "CORONADA CERAMIC",
      desc: 'Gloss White',
      size: '36MM',
      price: 7458,
      sex: 'women',
      product: 'watches',
    },
    {
      id: 5,
      img_1: "/DataImages/dataDetails/watches_women/id_5/1.jpg",
      img_2: "/DataImages/dataDetails/watches_women/id_5/2.jpg",
      img_3: "/DataImages/dataDetails/watches_women/id_5/3.mp4",
      img_4: "/DataImages/dataDetails/watches_women/id_5/4.jpg",
      img_5: "/DataImages/dataDetails/watches_women/id_5/5.jpg",
      img_6: "/DataImages/dataDetails/watches_women/id_5/6.jpg",
      img_7: "/DataImages/dataDetails/watches_women/id_5/7.jpg",
      video_1: "/DataImages/dataDetails/watches_women/id_5/8.mp4",
      img_9: "/DataImages/dataDetails/watches_women/id_5/9.jpeg",
      name: "Gloss White",
      desc: 'Siren Silver',
      size: '34MM',
      price: 7453,
      sex: 'women',
      product: 'watches',
    },
    {
      id: 6,
      img_1: "/DataImages/dataDetails/watches_women/id_6/1.jpg",
      img_2: "/DataImages/dataDetails/watches_women/id_6/2.jpg",
      img_3: "/DataImages/dataDetails/watches_women/id_6/3.mp4",
      img_4: "/DataImages/dataDetails/watches_women/id_6/4.jpg",
      img_5: "/DataImages/dataDetails/watches_women/id_6/5.jpg",
      img_6: "/DataImages/dataDetails/watches_women/id_6/6.jpg",
      img_7: "/DataImages/dataDetails/watches_women/id_6/7.jpg",
      img_8: "/DataImages/dataDetails/watches_women/id_6/8.jpeg",
      video_2: "/DataImages/dataDetails/watches_women/id_6/9.mp4",
      name: "NOVA CERAMIC ",
      desc: 'Gloss White',
      size: '38MM',
      price: 9341,
      sex: 'women',
      product: 'watches',
    },
    {
      id: 7,
      img_1: "/DataImages/dataDetails/watches_women/id_7/1.jpg",
      img_2: "/DataImages/dataDetails/watches_women/id_7/2.jpg",
      img_3: "/DataImages/dataDetails/watches_women/id_7/3.mp4",
      img_4: "/DataImages/dataDetails/watches_women/id_7/4.jpg",
      img_5: "/DataImages/dataDetails/watches_women/id_7/5.jpg",
      img_6: "/DataImages/dataDetails/watches_women/id_7/6.jpg",
      img_7: "/DataImages/dataDetails/watches_women/id_7/7.jpg",
      video_1: "/DataImages/dataDetails/watches_women/id_7/8.mp4",
      img_9: "/DataImages/dataDetails/watches_women/id_7/9.jpeg",
      name: "REINA MULTI EY ",
      desc: 'Siren Silver',
      size: '34MM',
      price: 7458,
      sex: 'women',
      product: 'watches',
    },
    {
      id: 8,
      img_1: "/DataImages/dataDetails/watches_women/id_8/1.jpg",
      img_2: "/DataImages/dataDetails/watches_women/id_8/2.jpg",
      img_3: "/DataImages/dataDetails/watches_women/id_8/3.mp4",
      img_4: "/DataImages/dataDetails/watches_women/id_8/4.jpg",
      img_5: "/DataImages/dataDetails/watches_women/id_8/5.jpg",
      img_6: "/DataImages/dataDetails/watches_women/id_8/6.jpg",
      img_7: "/DataImages/dataDetails/watches_women/id_8/7.jpg",
      video_1: "/DataImages/dataDetails/watches_women/id_8/8.mp4",
      video_2: "/DataImages/dataDetails/watches_women/id_8/9.mp4",
      name: "FROST",
      desc: 'Black Ice',
      size: '22MM',
      price: 5951,
      sex: 'women',
      product: 'watches',
    },
  ],
}













export const DataSunglasseDetails = {
  productSunglasseDataDetails: [
    {
      id: 1,
      img_1: "/DataImages/dataDetails/sunglasse_men/id_1/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_men/id_1/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_men/id_1/3.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'sunglasse',
    },
    {
      id: 2,
      img_1: "/DataImages/dataDetails/sunglasse_men/id_2/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_men/id_2/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_men/id_2/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_men/id_2/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_men/id_2/5.jpg",
      img_6: "/DataImages/dataDetails/sunglasse_men/id_2/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'sunglasse',
    },
    {
      id: 3,
      img_1: "/DataImages/dataDetails/sunglasse_men/id_3/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_men/id_3/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_men/id_3/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_men/id_3/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_men/id_3/5.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'sunglasse',
    },
    {
      id: 4,
      img_1: "/DataImages/dataDetails/sunglasse_men/id_4/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_men/id_4/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_men/id_4/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_men/id_4/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_men/id_4/5.jpg",
      img_6: "/DataImages/dataDetails/sunglasse_men/id_4/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'sunglasse',
    },
    {
      id: 5,
      img_1: "/DataImages/dataDetails/sunglasse_men/id_5/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_men/id_5/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_men/id_5/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_men/id_5/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_men/id_5/5.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'sunglasse',
    },
    {
      id: 6,
      img_1: "/DataImages/dataDetails/sunglasse_men/id_6/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_men/id_6/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_men/id_6/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_men/id_6/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_men/id_6/5.jpg",
      img_6: "/DataImages/dataDetails/sunglasse_men/id_6/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'sunglasse',
    },
    {
      id: 7,
      img_1: "/DataImages/dataDetails/sunglasse_men/id_7/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_men/id_7/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_men/id_7/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_men/id_7/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_men/id_7/5.jpg",
      img_6: "/DataImages/dataDetails/sunglasse_men/id_7/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'sunglasse',
    },
    {
      id: 8,
      img_1: "/DataImages/dataDetails/sunglasse_men/id_8/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_men/id_8/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_men/id_8/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_men/id_8/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_men/id_8/5.jpg",
      img_6: "/DataImages/dataDetails/sunglasse_men/id_8/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'sunglasse',
    },
    {
      id: 9,
      img_1: "/DataImages/dataDetails/sunglasse_men/id_9/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_men/id_9/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_men/id_9/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_men/id_9/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_men/id_9/5.jpg",
      img_6: "/DataImages/dataDetails/sunglasse_men/id_9/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'sunglasse',
    },
    {
      id: 10,
      img_1: "/DataImages/dataDetails/sunglasse_men/id_10/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_men/id_10/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_men/id_10/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_men/id_10/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_men/id_10/5.jpg",
      img_6: "/DataImages/dataDetails/sunglasse_men/id_10/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'sunglasse',
    },
    {
      id: 11,
      img_1: "/DataImages/dataDetails/sunglasse_men/id_11/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_men/id_11/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_men/id_11/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_men/id_11/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_men/id_11/5.jpg",
      img_6: "/DataImages/dataDetails/sunglasse_men/id_11/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'sunglasse',
    },



    // ------------------------------------- women ---------------------------------------------------
    {
      id: 1,
      img_1: "/DataImages/dataDetails/sunglasse_women/id_1/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_women/id_1/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_women/id_1/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_women/id_1/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_women/id_1/5.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'women',
      product: 'sunglasse',
    },
    {
      id: 2,
      img_1: "/DataImages/dataDetails/sunglasse_women/id_2/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_women/id_2/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_women/id_2/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_women/id_2/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_women/id_2/5.jpg",
      img_6: "/DataImages/dataDetails/sunglasse_women/id_2/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'women',
      product: 'sunglasse',
    },
    {
      id: 3,
      img_1: "/DataImages/dataDetails/sunglasse_women/id_3/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_women/id_3/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_women/id_3/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_women/id_3/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_women/id_3/5.jpg",
      img_6: "/DataImages/dataDetails/sunglasse_women/id_3/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'women',
      product: 'sunglasse',
    },
    {
      id: 4,
      img_1: "/DataImages/dataDetails/sunglasse_women/id_4/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_women/id_4/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_women/id_4/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_women/id_4/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_women/id_4/5.jpg",
      img_6: "/DataImages/dataDetails/sunglasse_women/id_4/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'women',
      product: 'sunglasse',
    },
    {
      id: 5,
      img_1: "/DataImages/dataDetails/sunglasse_women/id_5/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_women/id_5/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_women/id_5/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_women/id_5/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_women/id_5/5.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'women',
      product: 'sunglasse',
    },
    {
      id: 6,
      img_1: "/DataImages/dataDetails/sunglasse_women/id_6/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_women/id_6/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_women/id_6/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_women/id_6/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_women/id_6/5.jpg",
      img_6: "/DataImages/dataDetails/sunglasse_women/id_6/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'women',
      product: 'sunglasse',
    },
    {
      id: 7,
      img_1: "/DataImages/dataDetails/sunglasse_women/id_7/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_women/id_7/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_women/id_7/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_women/id_7/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_women/id_7/5.jpg",
      img_6: "/DataImages/dataDetails/sunglasse_women/id_7/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'women',
      product: 'sunglasse',
    },
    {
      id: 8,
      img_1: "/DataImages/dataDetails/sunglasse_women/id_8/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_women/id_8/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_women/id_8/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_women/id_8/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_women/id_8/5.jpg",
      img_6: "/DataImages/dataDetails/sunglasse_women/id_8/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'women',
      product: 'sunglasse',
    },
    {
      id: 9,
      img_1: "/DataImages/dataDetails/sunglasse_women/id_9/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_women/id_9/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_women/id_9/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_women/id_9/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_women/id_9/5.jpg",
      img_6: "/DataImages/dataDetails/sunglasse_women/id_9/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'women',
      product: 'sunglasse',
    },
    {
      id: 10,
      img_1: "/DataImages/dataDetails/sunglasse_women/id_10/1.jpg",
      img_2: "/DataImages/dataDetails/sunglasse_women/id_10/2.jpg",
      img_3: "/DataImages/dataDetails/sunglasse_women/id_10/3.jpg",
      img_4: "/DataImages/dataDetails/sunglasse_women/id_10/4.jpg",
      img_5: "/DataImages/dataDetails/sunglasse_women/id_10/5.jpg",
      img_6: "/DataImages/dataDetails/sunglasse_women/id_10/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'women',
      product: 'sunglasse',
    },
  ],
}
























export const DataJewelryDetails = {
  productJewelryDataDetails: [
    {
      id: 1,
      img_1: "/DataImages/dataDetails/jewelry_men/id_1/1.jpg",
      img_2: "/DataImages/dataDetails/jewelry_men/id_1/2.jpg",
      img_3: "/DataImages/dataDetails/jewelry_men/id_1/3.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',
      product: 'jewelry',
    },
    {
      id: 2,
      img_1: "/DataImages/dataDetails/jewelry_men/id_2/1.jpg",
      img_2: "/DataImages/dataDetails/jewelry_men/id_2/2.jpg",
      img_3: "/DataImages/dataDetails/jewelry_men/id_2/3.jpg",
      img_4: "/DataImages/dataDetails/jewelry_men/id_2/4.jpg",
      img_5: "/DataImages/dataDetails/jewelry_men/id_2/5.jpg",
      img_6: "/DataImages/dataDetails/jewelry_men/id_2/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',
      product: 'jewelry',
    },
    {
      id: 3,
      img_1: "/DataImages/dataDetails/jewelry_men/id_3/1.jpg",
      img_2: "/DataImages/dataDetails/jewelry_men/id_3/2.jpg",
      img_3: "/DataImages/dataDetails/jewelry_men/id_3/3.jpg",
      img_4: "/DataImages/dataDetails/jewelry_men/id_3/4.jpg",
      img_5: "/DataImages/dataDetails/jewelry_men/id_3/5.jpg",
      img_6: "/DataImages/dataDetails/jewelry_men/id_3/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',
      product: 'jewelry',
    },
    {
      id: 4,
      img_1: "/DataImages/dataDetails/jewelry_men/id_4/1.jpg",
      img_2: "/DataImages/dataDetails/jewelry_men/id_4/2.jpg",
      img_3: "/DataImages/dataDetails/jewelry_men/id_4/3.jpg",
      img_4: "/DataImages/dataDetails/jewelry_men/id_4/4.jpg",
      img_5: "/DataImages/dataDetails/jewelry_men/id_4/5.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'jewelry',
    },
    {
      id: 5,
      img_1: "/DataImages/dataDetails/jewelry_men/id_5/1.jpg",
      img_2: "/DataImages/dataDetails/jewelry_men/id_5/2.jpg",
      img_3: "/DataImages/dataDetails/jewelry_men/id_5/3.jpg",
      img_4: "/DataImages/dataDetails/jewelry_men/id_5/4.jpg",
      img_5: "/DataImages/dataDetails/jewelry_men/id_5/5.jpg",
      img_6: "/DataImages/dataDetails/jewelry_men/id_5/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'jewelry',
    },
    {
      id: 6,
      img_1: "/DataImages/dataDetails/jewelry_men/id_6/1.jpg",
      img_2: "/DataImages/dataDetails/jewelry_men/id_6/2.jpg",
      img_3: "/DataImages/dataDetails/jewelry_men/id_6/3.jpg",
      img_4: "/DataImages/dataDetails/jewelry_men/id_6/4.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'jewelry',
    },
    {
      id: 7,
      img_1: "/DataImages/dataDetails/jewelry_men/id_7/1.jpg",
      img_2: "/DataImages/dataDetails/jewelry_men/id_7/2.jpg",
      img_3: "/DataImages/dataDetails/jewelry_men/id_7/3.jpg",
      img_4: "/DataImages/dataDetails/jewelry_men/id_7/4.jpg",
      img_5: "/DataImages/dataDetails/jewelry_men/id_7/5.jpg",
      img_6: "/DataImages/dataDetails/jewelry_men/id_7/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'jewelry',
    },
    {
      id: 8,
      img_1: "/DataImages/dataDetails/jewelry_men/id_8/1.jpg",
      img_2: "/DataImages/dataDetails/jewelry_men/id_8/2.jpg",
      img_3: "/DataImages/dataDetails/jewelry_men/id_8/3.jpg",
      img_4: "/DataImages/dataDetails/jewelry_men/id_8/4.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'jewelry',
    },
    {
      id: 9,
      img_1: "/DataImages/dataDetails/jewelry_men/id_9/1.jpg",
      img_2: "/DataImages/dataDetails/jewelry_men/id_9/2.jpg",
      img_3: "/DataImages/dataDetails/jewelry_men/id_9/3.jpg",
      img_4: "/DataImages/dataDetails/jewelry_men/id_9/4.jpeg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'jewelry',
    },
    {
      id: 10,
      img_1: "/DataImages/dataDetails/jewelry_men/id_10/1.jpg",
      img_2: "/DataImages/dataDetails/jewelry_men/id_10/2.jpg",
      img_3: "/DataImages/dataDetails/jewelry_men/id_10/3.jpg",
      img_4: "/DataImages/dataDetails/jewelry_men/id_10/4.jpg",
      img_5: "/DataImages/dataDetails/jewelry_men/id_10/5.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'jewelry',
    },
    {
      id: 11,
      img_1: "/DataImages/dataDetails/jewelry_men/id_11/1.jpg",
      img_2: "/DataImages/dataDetails/jewelry_men/id_11/2.jpg",
      img_3: "/DataImages/dataDetails/jewelry_men/id_11/3.jpg",
      img_4: "/DataImages/dataDetails/jewelry_men/id_11/4.jpg",
      img_5: "/DataImages/dataDetails/jewelry_men/id_11/5.jpg",
      img_6: "/DataImages/dataDetails/jewelry_men/id_11/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'jewelry',
    },
    {
      id: 12,
      img_1: "/DataImages/dataDetails/jewelry_men/id_12/1.jpg",
      img_2: "/DataImages/dataDetails/jewelry_men/id_12/2.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'men',

      product: 'jewelry',
    },



    // ----------------------------------------- women -----------------------------------------------------------------
    {
      id: 1,
      img_1: "/DataImages/dataDetails/jewelry_women/id_1/1.jpg",
      img_2: "/DataImages/dataDetails/jewelry_women/id_1/2.jpg",
      img_3: "/DataImages/dataDetails/jewelry_women/id_1/3.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'women',
      product: 'jewelry',
    },
    {
      id: 2,
      img_1: "/DataImages/dataDetails/jewelry_women/id_2/1.jpg",
      img_2: "/DataImages/dataDetails/jewelry_women/id_2/2.jpg",
      img_3: "/DataImages/dataDetails/jewelry_women/id_2/3.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'women',
      product: 'jewelry',
    },
    {
      id: 3,
      img_1: "/DataImages/dataDetails/jewelry_women/id_3/1.jpg",
      img_2: "/DataImages/dataDetails/jewelry_women/id_3/2.jpg",
      img_3: "/DataImages/dataDetails/jewelry_women/id_3/3.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'women',
      product: 'jewelry',
    },
    {
      id: 4,
      img_1: "/DataImages/dataDetails/jewelry_women/id_4/1.jpg",
      img_2: "/DataImages/dataDetails/jewelry_women/id_4/2.jpg",
      img_3: "/DataImages/dataDetails/jewelry_women/id_4/3.jpg",
      img_4: "/DataImages/dataDetails/jewelry_women/id_4/4.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'women',
      product: 'jewelry',
    },
    {
      id: 5,
      img_1: "/DataImages/dataDetails/jewelry_women/id_5/1.jpg",
      img_2: "/DataImages/dataDetails/jewelry_women/id_5/2.jpg",
      img_3: "/DataImages/dataDetails/jewelry_women/id_5/3.jpg",
      img_4: "/DataImages/dataDetails/jewelry_women/id_5/4.jpg",
      img_5: "/DataImages/dataDetails/jewelry_women/id_5/5.jpg",
      img_6: "/DataImages/dataDetails/jewelry_women/id_5/6.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'women',
      product: 'jewelry',
    },
    {
      id: 6,
      img_1: "/DataImages/dataDetails/jewelry_women/id_6/1.jpg",
      img_2: "/DataImages/dataDetails/jewelry_women/id_6/2.jpg",
      img_3: "/DataImages/dataDetails/jewelry_women/id_6/3.jpg",
      img_4: "/DataImages/dataDetails/jewelry_women/id_6/4.jpg",
      name: "RAPTOR",
      size: '46.5MM',
      desc: 'Raptor Automatic',
      price: 18658,
      sex: 'women',
      product: 'jewelry',
    },
  ],
}


