const DataJewelryWomen = {
  productDataJewelryWomen: [
    {
      id: 1,
      cover: "/DataImages/jewelry/women/jewelry_w_1.jpg",
      name: "RAPTOR ",
      desc: 'Raptor Automatic',
      size: '42 MM',
      price: 18658,
      sex: 'women',
      product: 'jewelry',
      display: 1,
    },
    {
      id: 2,
      cover: "/DataImages/jewelry/women/jewelry_w_2.jpg",
      name: "RAPTOR ",
      desc: 'Raptor Automatic',
      size: '42 MM',
      price: 18658,
      sex: 'women',
      product: 'jewelry',
      display: 2,
    },
    {
      id: 3,
      cover: "/DataImages/jewelry/women/jewelry_w_3.jpg",
      name: "RAPTOR ",
      desc: 'Raptor Automatic',
      size: '42 MM',
      price: 18658,
      sex: 'women',
      product: 'jewelry',
      display: 3,
    },
    {
      id: 4,
      cover: "/DataImages/jewelry/women/jewelry_w_4.jpg",
      name: "RAPTOR ",
      desc: 'Raptor Automatic',
      size: '42 MM',
      price: 18658,
      sex: 'women',
      product: 'jewelry',
      display: 4,
    },
    {
      id: 5,
      cover: "/DataImages/jewelry/women/jewelry_w_5.jpg",
      name: "RAPTOR ",
      desc: 'Raptor Automatic',
      size: '42 MM',
      price: 18658,
      sex: 'women',
      product: 'jewelry',
      display: 5,
    },
    {
      id: 6,
      cover: "/DataImages/jewelry/women/jewelry_w_6.jpg",
      name: "RAPTOR ",
      desc: 'Raptor Automatic',
      size: '42 MM',
      price: 18658,
      sex: 'women',
      product: 'jewelry',
      display: 6,
    },
  ]
}

export default DataJewelryWomen