const DataSunglasseMen = {
  productDataSunglasseMen: [
    {
      id: 1,
      cover: "/DataImages/sunglasse/men/sunglasse_m_1.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 1,
      sex: 'men',
      product: 'sunglasse',
    },
    {
      id: 2,
      cover: "/DataImages/sunglasse/men/sunglasse_m_2.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 2,
      sex: 'men',
      product: 'sunglasse',
    },
    {
      id: 3,
      cover: "/DataImages/sunglasse/men/sunglasse_m_3.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 3,
      sex: 'men',
      product: 'sunglasse',
    },
    {
      id: 4,
      cover: "/DataImages/sunglasse/men/sunglasse_m_4.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 4,
      sex: 'men',
      product: 'sunglasse',
    },
    {
      id: 5,
      cover: "/DataImages/sunglasse/men/sunglasse_m_5.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 5,
      sex: 'men',
      product: 'sunglasse',
    },
    {
      id: 6,
      cover: "/DataImages/sunglasse/men/sunglasse_m_6.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 6,
      sex: 'men',
      product: 'sunglasse',
    },
    {
      id: 7,
      cover: "/DataImages/sunglasse/men/sunglasse_m_7.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 7,
      sex: 'men',
      product: 'sunglasse',
    },
    {
      id: 8,
      cover: "/DataImages/sunglasse/men/sunglasse_m_8.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 8,
      sex: 'men',
      product: 'sunglasse',
    },
    {
      id: 9,
      cover: "/DataImages/sunglasse/men/sunglasse_m_9.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 9,
      sex: 'men',
      product: 'sunglasse',
    },
    {
      id: 10,
      cover: "/DataImages/sunglasse/men/sunglasse_m_10.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 10,
      sex: 'men',
      product: 'sunglasse',
    },
    {
      id: 11,
      cover: "/DataImages/sunglasse/men/sunglasse_m_11.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 11,
      sex: 'men',
      product: 'sunglasse',
    },
  ]
}

export default DataSunglasseMen