const DataSunglasseWomen = {
  productDataSunglasseWomen: [
    {
      id: 1,
      cover: "/DataImages/sunglasse/women/sunglasse_w_1.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 1,
      sex: 'women',
      product: 'sunglasse',
    },
    {
      id: 2,
      cover: "/DataImages/sunglasse/women/sunglasse_w_2.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 2,
      sex: 'women',
      product: 'sunglasse',
    },
    {
      id: 3,
      cover: "/DataImages/sunglasse/women/sunglasse_w_3.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 3,
      sex: 'women',
      product: 'sunglasse',
    },
    {
      id: 4,
      cover: "/DataImages/sunglasse/women/sunglasse_w_4.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 3,
      sex: 'women',
      product: 'sunglasse',
    },
    {
      id: 5,
      cover: "/DataImages/sunglasse/women/sunglasse_w_5.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 5,
      sex: 'women',
      product: 'sunglasse',
    },
    {
      id: 6,
      cover: "/DataImages/sunglasse/women/sunglasse_w_6.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 6,
      sex: 'women',
      product: 'sunglasse',
    },
    {
      id: 7,
      cover: "/DataImages/sunglasse/women/sunglasse_w_7.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 7,
      sex: 'women',
      product: 'sunglasse',
    },
    {
      id: 8,
      cover: "/DataImages/sunglasse/women/sunglasse_w_8.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 8,
      sex: 'women',
      product: 'sunglasse',
    },
    {
      id: 9,
      cover: "/DataImages/sunglasse/women/sunglasse_w_9.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 9,
      sex: 'women',
      product: 'sunglasse',
    },
    {
      id: 10,
      cover: "/DataImages/sunglasse/women/sunglasse_w_10.jpg",
      name: "RAPTO",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 10,
      sex: 'women',
      product: 'sunglasse',
    },
  ]
}

export default DataSunglasseWomen