const DataWatchesWomen = {
  productDataWatchesWomen: [
    {
      id: 1,
      cover: "../DataImages/watches/women/watches_w_1.jpg",
      name: "SIGNATURE SQUARE",
      desc: 'Charlie Gold',
      size: '24MM',
      price: 4821,
      display: 1,
      sex: 'women',
      product: 'watches',
    },
    {
      id: 2,
      cover: "../DataImages/watches/women/watches_w_2.jpg",
      name: "SIGNATURE SQUARE CERAMIC ",
      desc: 'Gloss White',
      size: '26MM',
      price: 8588,
      display: 2,
      sex: 'women',
      product: 'watches',
    },
    {
      id: 3,
      cover: "../DataImages/watches/women/watches_w_3.jpg",
      name: "SIGNATURE SQUARE CERAMIC",
      desc: ' Cashmere Taupe',
      size: '26MM',
      price: 8588,
      display: 3,
      sex: 'women',
      product: 'watches',
    },
    {
      id: 4,
      cover: "../DataImages/watches/women/watches_w_4.jpg",
      name: "CORONADA CERAMIC",
      desc: 'Gloss White',
      size: '36MM',
      price: 7458,
      display: 4,
      sex: 'women',
      product: 'watches',
    },
    {
      id: 5,
      cover: "../DataImages/watches/women/watches_w_5.jpg",
      name: "Gloss White",
      desc: 'Siren Silver',
      size: '34MM',
      price: 7453,
      display: 5,
      sex: 'women',
      product: 'watches',
    },
    {
      id: 6,
      cover: "../DataImages/watches/women/watches_w_6.jpg",
      name: "NOVA CERAMIC ",
      desc: 'Gloss White',
      size: '38MM',
      price: 9341,
      display: 6,
      sex: 'women',
      product: 'watches',
    },
    {
      id: 7,
      cover: "../DataImages/watches/women/watches_w_7.jpg",
      name: "REINA MULTI EY ",
      desc: 'Siren Silver',
      size: '34MM',
      price: 7458,
      display: 7,
      sex: 'women',
      product: 'watches',
    },
    {
      id: 8,
      cover: "../DataImages/watches/women/watches_w_8.jpg",
      name: "FROST",
      desc: 'Black Ice',
      size: '22MM',
      price: 5951,
      display: 7,
      sex: 'women',
      product: 'watches',
    },
  ]
}

export default DataWatchesWomen