const DataWatchesMen = {
  productDataWatchesMen: [
    {
      id: 1,
      cover: "/DataImages/watches/men/watches_m_1.jpg",
      name: "RAPTOR | 46.5MM",
      desc: 'Raptor Automatic',
      price: 18658,
      display: 1,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 2,
      cover: "/DataImages/watches/men/watches_m_2.jpg",
      name: "CHRONO CERAMIC | 45MM",
      desc: 'Gloss White',
      price: 11165,
      display: 2,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 3,
      cover: "/DataImages/watches/men/watches_m_3.jpg",
      name: "CHRONO CERAMIC | 45MM",
      desc: 'Midnight Blue',
      price: 11100,
      display: 3,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 4,
      cover: "/DataImages/watches/men/watches_m_4.jpg",
      name: "AIRHAWK | 42MM",
      desc: 'Skyline Silver',
      price: 8580,
      display: 4,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 5,
      cover: "/DataImages/watches/men/watches_m_5.jpg",
      name: "LEGACY SLIM | 42MM",
      desc: 'Panther Black',
      price: 4421,
      display: 5,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 6,
      cover: "/DataImages/watches/men/watches_m_6.jpg",
      name: "AIRHAWK | 42MM",
      desc: 'Honey Smoke',
      price: 8543,
      display: 6,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 7,
      cover: "/DataImages/watches/men/watches_m_7.jpg",
      name: "LEGACY SLIM | 42MM",
      desc: 'Manta Blue',
      price: 4421,
      display: 7,
      sex: 'men',
      product: 'watches',
      group: 1,
    },
    {
      id: 8,
      cover: "/DataImages/watches/men/watches_m_8.jpg",
      name: "LEGACY SLIM | 42MM",
      desc: 'Eagle Tan',
      price: 4421,
      display: 8,
      sex: 'men',
      product: 'watches',
      group: 1,
    },
    {
      id: 9,
      cover: "/DataImages/watches/men/watches_m_9.jpg",
      name: "AIRHAWK | 42MM",
      desc: 'Stealth Black',
      price: 8500,
      display: 9,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 10,
      cover: "/DataImages/watches/men/watches_m_10.jpg",
      name: "RAPTOR | 46.5MM",
      desc: 'Moon Silver',
      price: 9292,
      display: 10,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 11,
      cover: "/DataImages/watches/men/watches_m_11.jpg",
      name: "AIRHAWK | 42MM",
      desc: 'Maple Frost',
      price: 8540,
      display: 11,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 12,
      cover: "/DataImages/watches/men/watches_m_12.jpg",
      name: "LEGACY SLIM | 42MM",
      desc: 'Grizzly Brown',
      price: 4400,
      display: 12,
      sex: 'men',
      product: 'watches',
      group: 1,
    },
    {
      id: 13,
      cover: "/DataImages/watches/men/watches_m_13.jpg",
      name: "ELEMENT CERAMIC | 43MM",
      desc: 'Gloss White',
      price: 8300,
      display: 13,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 14,
      cover: "/DataImages/watches/men/watches_m_14.jpg",
      name: "BLACKTOP | 47MM",
      desc: 'Astro Blue',
      price: 9292,
      display: 14,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 15,
      cover: "/DataImages/watches/men/watches_m_15.jpg",
      name: "LEGACY SLIM | 42MM",
      desc: 'Phoenix Gold',
      price: 4790,
      display: 15,
      sex: 'men',
      product: 'watches',
      group: 1,
    },
    {
      id: 16,
      cover: "/DataImages/watches/men/watches_m_16.jpg",
      name: "VOYAGER | 42MM",
      desc: 'Eclipse Gold',
      price: 5902,
      display: 16,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 17,
      cover: "/DataImages/watches/men/watches_m_17.jpg",
      name: "BLACKTOP | 47MM",
      desc: 'Champion Gold',
      price: 9292,
      display: 17,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 18,
      cover: "/DataImages/watches/men/watches_m_18.jpg",
      name: "BLACKTOP | 47MM",
      desc: 'Rallye Green',
      price: 9292,
      display: 18,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 19,
      cover: "/DataImages/watches/men/watches_m_19.jpg",
      name: "RAPTOR | 46.5MM",
      desc: 'Honey Smoke',
      price: 9929,
      display: 19,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 20,
      cover: "/DataImages/watches/men/watches_m_20.jpg",
      name: "ELEMENT CERAMIC | 43MM",
      desc: 'Midnight Blue',
      price: 6009,
      display: 20,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 21,
      cover: "/DataImages/watches/men/watches_m_21.jpg",
      name: "ELEMENT CERAMIC | 43MM",
      desc: 'Midnight Blue',
      price: 4543,
      display: 21,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 22,
      cover: "/DataImages/watches/men/watches_m_22.jpg",
      name: "ELEMENT CERAMIC | 43MM",
      desc: 'Midnight Blue',
      price: 4355,
      display: 22,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 23,
      cover: "/DataImages/watches/men/watches_m_23.jpg",
      name: "ELEMENT CERAMIC | 43MM",
      desc: 'Midnight Blue',
      price: 3456,
      display: 23,
      sex: 'men',
      product: 'watches',
    },
  ]
}

export default DataWatchesMen