
const DataTrending = {
  productTrendingData: [
    {
      id: 9,
      cover: "./DataImages/trending/watches_m_t_9.jpg",
      name: "AIRHAWK | 42MM",
      desc: 'Stealth Black',
      price: 8500,
      trending: true,
      display: 9,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 6,
      cover: "./DataImages/trending/watches_m_t_2.jpg",
      name: "NOVA CERAMIC ",
      desc: 'Gloss White',
      size: '38MM',
      price: 9341,
      trending: true,
      sex: 'women',
      product: 'watches',
    },
    {
      id: 23,
      cover: "./DataImages/trending/watches_m_t_3.jpg",
      name: "watches_1",
      desc: 'loremloremlor',
      price: 2500,
      trending: true,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 24,
      cover: "./DataImages/trending/watches_m_t_4.jpg",
      name: "watches_1",
      desc: 'loremloremlor',
      price: 2500,
      trending: true,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 14,
      cover: "./DataImages/trending/watches_m_t_5.jpg",
      name: "BLACKTOP | 47MM",
      desc: 'Astro Blue',
      price: 9292,
      trending: true,
      display: 14,
      sex: 'men',
      product: 'watches',
    },
    {
      id: 18,
      cover: "./DataImages/trending/watches_m_t_6.jpg",
      name: "BLACKTOP | 47MM",
      desc: 'Rallye Green',
      price: 9292,
      trending: true,
      display: 18,
      sex: 'men',
      product: 'watches',
    },
  ],
}

export default DataTrending